name: prism_flutter_core
description: Prism provides foundations to build modular flutter apps
version: 0.0.1
homepage: https://github.com/metaflowltd/prism_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  get_it: ^7.2.0
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
